#ifndef PROTOCOLS_H
#define PROTOCOLS_H

#define MESSAGE_END_MARKER 255

#define MESSAGE_START_MARKERS_AMOUNT 3

#define MOVEMENT_PAYLOAD_SIZE 2

#define MOVEMENT_COMMAND 0x81
#define SEND_DATA_COMMAND 0x82

#define SSID_COMMAND 0xA0
#define NETWORK_PASSWORD_COMMAND 0xB0

#endif